### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by JayFoxRox** [PsiLupan/FRAY#4]
Please add a README, see #3 for questions it should answer.
Also should explain the name - as it's cryptic (for non-native-speakers) and makes this project hard to find.

*(And while you don't use it, please disable GitHub "Projects" and GitHub "Wiki" - those links do nothing for users and are just confusing)*

**Comment by PsiLupan** [comment]
Thanks, I just took care of the wiki. I'm leaving the project board up, so that I'll remember to actually use it.

Regarding the name, it's a synonym to Melee without being Brawl. Originally the name of the project was MeleeRecompiled and I decided that it would be best to distance from using the original name. I'll make note of it in the README, once I write it up.
