### ISSUE TITLE
Is all of this ported over to the new decompilation repo?

### ISSUE THREAD

**Issue by stephenjayakar** [PsiLupan/FRAY#75]
I was cross-checking between repos and it seems like some of the things decompiled here aren't decompiled over there (specifically noticed this for the ftFox file). is anyone doing this already?

**Comment by PsiLupan** [comment]
I was originally, but part of the problem is we don't have the actual compiler that Melee used. We've done a lot of digging and they apparently were using a compiler even earlier than the one shipped in CodeWarrior for Dolphin 1.0.

As a result, our close approximation compiler has functions that aren't matching correctly when they should and I've largely taken a break from the project while the compiler is located.

**Comment by stephenjayakar** [comment]
👍
